name: Build VB.NET EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore BTMOB.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild BTMOB.sln /p:Configuration=Release

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: BTMob-EXE
        path: |
          **/bin/Release/*.exe
